all: strncmp_test

strncmp_test:
	g++ -g strncmp_test.cc -o strncmp_test 

consequtive_subset:
	g++ -g int_to_string.cc -o int_to_string 

consequtive_subset:
	g++ -g consequtive_subset.cc -o consequtive_subset 
