all: restore_ip invertTree word_search dictionary

dictionary:
	g++ -g dictionary.cc -o dictionary

word_search:
	g++ -g word_search.cc -o word_search

invertTree:
	g++ -g invertTree.cc -o invertTree

restore_ip:
	g++ -g restore_ip.cc -o restore_ip

clean:
	rm *.o
