all: alienDict
TARGET = alienDict
alienDict:
	g++ -g -std=c++11 alienDict.cc -o alienDict
fractile:
	g++ -g -std=c++11 fractile.cc -o fractile
coin:
	g++ -g -std=c++11 coin.cc -o coin
flip:
	g++ -g -std=c++11 flip.cc -o flip
countSheep:
	g++ -g -std=c++11 countSheep.cc -o countSheep
sumRange:
	g++ -g -std=c++11 sumRange.cc -o sumRange
removeInvalid:
	g++ -g removeInvalidParenthesis.cc -o removeInvalidParenthsis

move_zeros:
	g++ -g move_zeros.cc -o move_zeros

dictionary:
	g++ -g dictionary.cc -o dictionary

word_search:
	g++ -g word_search.cc -o word_search

invertTree:
	g++ -g invertTree.cc -o invertTree

restore_ip:
	g++ -g restore_ip.cc -o restore_ip

clean:
	rm -rf $(TARGET)
